CREATE TABLE "Users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "username" varchar UNIQUE NOT NULL,
  "passwordHash" varchar NOT NULL,
  "emailVerified" boolean,
  "status" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp,
  "lastLoginAt" timestamp
);

CREATE TABLE "Roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "roleName" varchar UNIQUE,
  "createdAt" timestamp
);

CREATE TABLE "UserRoles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "roleId" integer NOT NULL,
  "createdAt" timestamp
);

CREATE TABLE "UserProfile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer UNIQUE NOT NULL,
  "firstName" varchar,
  "lastName" varchar,
  "profileImage" varchar,
  "bio" text,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "TournamentOrganizerDetails" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "mobileNumber" varchar,
  "governmentIdUri" varchar,
  "selfieVerificationUri" varchar,
  "verificationStatus" varchar,
  "verifiedAt" timestamp,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "BrandDetails" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "brandName" varchar,
  "mobileNumber" varchar,
  "websiteUrl" varchar,
  "legalEntityIdentifier" varchar,
  "businessAddress" text,
  "verificationStatus" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "InfluencerDetails" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "mobileNumber" varchar,
  "aboutYourself" text,
  "accountStatus" varchar,
  "verificationStatus" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "SocialMediaPlatform" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "platformName" varchar,
  "urlPrefix" varchar,
  "createdAt" timestamp
);

CREATE TABLE "SocialMediaAccount" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "platformId" integer NOT NULL,
  "accountName" varchar,
  "profileUrl" varchar,
  "followersCount" bigint,
  "subscriberCount" bigint,
  "viewSubscriptionRatio" decimal,
  "viewCommentRatio" decimal,
  "acceptanceStatusId" integer,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "StatusMaster" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "statusType" varchar,
  "statusName" varchar,
  "createdAt" timestamp
);

CREATE TABLE "Game" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gameName" varchar,
  "gameType" varchar,
  "gameMode" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "InfluencerGame" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "influencerId" integer,
  "gameId" integer,
  "isPrimary" boolean,
  "createdAt" timestamp
);

CREATE TABLE "TournamentCategory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categoryName" varchar,
  "createdAt" timestamp
);

CREATE TABLE "TournamentType" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categoryId" integer,
  "typeName" varchar,
  "createdAt" timestamp
);

CREATE TABLE "SeedingType" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "createdAt" timestamp
);

CREATE TABLE "Tournament" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organizerId" integer,
  "name" varchar,
  "description" text,
  "registrationStartDate" datetime,
  "registrationEndDate" datetime,
  "tournamentStartDate" datetime,
  "tournamentEndDate" datetime,
  "bannerFileId" integer,
  "categoryId" integer,
  "tournamentTypeId" integer,
  "maximumTeams" integer,
  "maximumPlayersPerTeam" integer,
  "seedingTypeId" integer,
  "entryFee" decimal,
  "verificationRequired" boolean,
  "packageId" integer,
  "status" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "RulesCategory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categoryName" varchar,
  "createdAt" timestamp
);

CREATE TABLE "TournamentRule" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tournamentId" integer,
  "categoryId" integer,
  "ruleText" text,
  "createdBy" integer,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "PrizeCategory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "createdAt" timestamp
);

CREATE TABLE "TournamentPrize" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tournamentId" integer,
  "prizeCategoryId" integer,
  "positionName" varchar,
  "rankOrder" integer,
  "prizeAmount" decimal,
  "prizeDescription" text,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "Team" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ownerId" integer,
  "teamName" varchar,
  "teamLogoFileId" integer,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "TeamPosition" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "createdAt" timestamp
);

CREATE TABLE "TeamMember" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teamId" integer,
  "userId" integer,
  "positionId" integer,
  "joinedAt" timestamp,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "TournamentRegistration" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tournamentId" integer,
  "teamId" integer,
  "registrationStatusId" integer,
  "registrationDate" timestamp,
  "approvedBy" integer,
  "approvedDate" timestamp,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "TournamentRegistrationPayment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "registrationId" integer,
  "tournamentId" integer,
  "participantId" integer,
  "amount" decimal,
  "paymentReference" varchar,
  "paymentStatus" varchar,
  "paidDate" timestamp,
  "createdAt" timestamp
);

CREATE TABLE "TournamentAnnouncement" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tournamentId" integer,
  "title" varchar,
  "content" text,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "TournamentFAQ" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tournamentId" integer,
  "userId" integer,
  "question" text,
  "answer" text,
  "status" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "CampaignType" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "createdAt" timestamp
);

CREATE TABLE "Campaign" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brandId" integer,
  "campaignTypeId" integer,
  "campaignName" varchar,
  "gameId" integer,
  "startDate" datetime,
  "endDate" datetime,
  "description" text,
  "campaignThumbnailFileId" integer,
  "totalBudget" decimal,
  "influencerCost" decimal,
  "additionalExpenses" decimal,
  "status" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "CampaignPlatform" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaignId" integer,
  "platformId" integer
);

CREATE TABLE "CampaignAsset" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaignId" integer,
  "assetType" varchar,
  "fileId" integer,
  "createdAt" timestamp
);

CREATE TABLE "CampaignDeliverable" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaignId" integer,
  "fileId" integer,
  "createdAt" timestamp
);

CREATE TABLE "CollaborationRequest" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "senderId" integer,
  "receiverId" integer,
  "campaignId" integer,
  "title" varchar,
  "description" text,
  "proposedAmount" decimal,
  "status" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "PaymentMethod" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "methodName" varchar,
  "createdAt" timestamp
);

CREATE TABLE "TransactionType" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "typeName" varchar,
  "createdAt" timestamp
);

CREATE TABLE "RevenueTransaction" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transactionTypeId" integer,
  "entityType" varchar,
  "entityId" integer,
  "referenceId" varchar,
  "userId" integer,
  "amount" decimal,
  "paymentMethodId" integer,
  "paymentReference" varchar,
  "paymentStatus" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "TournamentPackage" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "price" decimal,
  "maxTeams" integer,
  "isActive" boolean,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "TournamentPayment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organizerId" integer,
  "tournamentId" integer,
  "packageId" integer,
  "amount" decimal,
  "paymentReference" varchar,
  "paymentStatus" varchar,
  "paidDate" timestamp,
  "createdAt" timestamp
);

CREATE TABLE "SubscriptionPlan" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "userType" varchar,
  "price" decimal,
  "durationDays" integer,
  "isActive" boolean,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "UserSubscription" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer,
  "subscriptionPlanId" integer,
  "startDate" timestamp,
  "endDate" timestamp,
  "amountPaid" decimal,
  "status" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "Files" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fileName" varchar,
  "fileType" varchar,
  "bucketName" varchar,
  "storagePath" varchar,
  "fileSize" bigint,
  "uploadedBy" integer,
  "createdAt" timestamp
);

CREATE TABLE "Notification" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer,
  "title" varchar,
  "message" text,
  "isRead" boolean,
  "createdAt" timestamp
);

CREATE TABLE "AuditLog" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer,
  "entityName" varchar,
  "entityId" integer,
  "actionType" varchar,
  "oldValue" json,
  "newValue" json,
  "ipAddress" varchar,
  "userAgent" text,
  "createdAt" timestamp
);

CREATE TABLE "Conversation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversationType" varchar NOT NULL,
  "name" varchar,
  "description" text,
  "groupImageFileId" integer,
  "createdBy" integer NOT NULL,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "ConversationParticipant" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversationId" integer NOT NULL,
  "userId" integer NOT NULL,
  "isAdmin" boolean,
  "isMuted" boolean,
  "joinedAt" timestamp,
  "leftAt" timestamp,
  "createdAt" timestamp
);

CREATE TABLE "Message" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversationId" integer NOT NULL,
  "senderId" integer NOT NULL,
  "messageType" varchar NOT NULL,
  "content" text,
  "replyMessageId" bigint,
  "isEdited" boolean,
  "editedAt" timestamp,
  "isDeleted" boolean,
  "deletedAt" timestamp,
  "createdAt" timestamp
);

CREATE TABLE "MessageAttachment" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "messageId" bigint NOT NULL,
  "fileId" integer NOT NULL,
  "createdAt" timestamp
);

CREATE TABLE "MessageReadStatus" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "messageId" bigint NOT NULL,
  "userId" integer NOT NULL,
  "readAt" timestamp
);

CREATE TABLE "MessageReaction" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "messageId" bigint NOT NULL,
  "userId" integer NOT NULL,
  "reaction" varchar,
  "createdAt" timestamp
);

CREATE TABLE "UserPresence" (
  "userId" integer PRIMARY KEY,
  "isOnline" boolean,
  "currentSocketId" varchar,
  "lastSeenAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "ConversationPinnedMessage" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversationId" integer NOT NULL,
  "messageId" bigint NOT NULL,
  "pinnedBy" integer,
  "pinnedAt" timestamp
);

CREATE TABLE "ConversationSettings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversationId" integer UNIQUE,
  "allowMemberMessaging" boolean,
  "allowMemberInvite" boolean,
  "onlyAdminCanPost" boolean,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "AffiliateCampaign" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brandId" integer NOT NULL,
  "campaignName" varchar NOT NULL,
  "description" text,
  "startDate" datetime,
  "endDate" datetime,
  "status" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "AffiliateLink" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "affiliateCampaignId" integer NOT NULL,
  "assignedUserId" integer NOT NULL,
  "assignedUserType" varchar,
  "linkName" varchar,
  "destinationUrl" varchar NOT NULL,
  "shortCode" varchar UNIQUE NOT NULL,
  "status" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "AffiliateClick" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "affiliateLinkId" integer NOT NULL,
  "sessionId" varchar,
  "visitorIp" varchar,
  "country" varchar,
  "city" varchar,
  "deviceType" varchar,
  "browser" varchar,
  "refererUrl" varchar,
  "clickedAt" timestamp
);

COMMENT ON COLUMN "Conversation"."conversationType" IS 'Direct | Group';

COMMENT ON COLUMN "Message"."messageType" IS 'Text | Image | Video | File | System';

COMMENT ON COLUMN "MessageReaction"."reaction" IS '👍 ❤️ 😂 🔥 😢 😮';

COMMENT ON COLUMN "AffiliateLink"."assignedUserType" IS 'Influencer | TournamentOrganizer';

ALTER TABLE "AffiliateLink" ADD FOREIGN KEY ("affiliateCampaignId") REFERENCES "AffiliateCampaign" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AffiliateLink" ADD FOREIGN KEY ("assignedUserId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AffiliateClick" ADD FOREIGN KEY ("affiliateLinkId") REFERENCES "AffiliateLink" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Conversation" ADD FOREIGN KEY ("createdBy") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ConversationParticipant" ADD FOREIGN KEY ("conversationId") REFERENCES "Conversation" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ConversationParticipant" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Message" ADD FOREIGN KEY ("conversationId") REFERENCES "Conversation" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Message" ADD FOREIGN KEY ("senderId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Message" ADD FOREIGN KEY ("replyMessageId") REFERENCES "Message" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "MessageAttachment" ADD FOREIGN KEY ("messageId") REFERENCES "Message" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "MessageAttachment" ADD FOREIGN KEY ("fileId") REFERENCES "Files" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "MessageReadStatus" ADD FOREIGN KEY ("messageId") REFERENCES "Message" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "MessageReadStatus" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "MessageReaction" ADD FOREIGN KEY ("messageId") REFERENCES "Message" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "MessageReaction" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "UserPresence" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ConversationPinnedMessage" ADD FOREIGN KEY ("conversationId") REFERENCES "Conversation" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ConversationPinnedMessage" ADD FOREIGN KEY ("messageId") REFERENCES "Message" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ConversationPinnedMessage" ADD FOREIGN KEY ("pinnedBy") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ConversationSettings" ADD FOREIGN KEY ("conversationId") REFERENCES "Conversation" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "UserRoles" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "UserRoles" ADD FOREIGN KEY ("roleId") REFERENCES "Roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "UserProfile" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentOrganizerDetails" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "BrandDetails" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "InfluencerDetails" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SocialMediaAccount" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SocialMediaAccount" ADD FOREIGN KEY ("platformId") REFERENCES "SocialMediaPlatform" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SocialMediaAccount" ADD FOREIGN KEY ("acceptanceStatusId") REFERENCES "StatusMaster" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "InfluencerGame" ADD FOREIGN KEY ("influencerId") REFERENCES "InfluencerDetails" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "InfluencerGame" ADD FOREIGN KEY ("gameId") REFERENCES "Game" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentType" ADD FOREIGN KEY ("categoryId") REFERENCES "TournamentCategory" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Tournament" ADD FOREIGN KEY ("organizerId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Tournament" ADD FOREIGN KEY ("categoryId") REFERENCES "TournamentCategory" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Tournament" ADD FOREIGN KEY ("tournamentTypeId") REFERENCES "TournamentType" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Tournament" ADD FOREIGN KEY ("seedingTypeId") REFERENCES "SeedingType" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Tournament" ADD FOREIGN KEY ("packageId") REFERENCES "TournamentPackage" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentRule" ADD FOREIGN KEY ("tournamentId") REFERENCES "Tournament" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentRule" ADD FOREIGN KEY ("categoryId") REFERENCES "RulesCategory" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentPrize" ADD FOREIGN KEY ("tournamentId") REFERENCES "Tournament" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentPrize" ADD FOREIGN KEY ("prizeCategoryId") REFERENCES "PrizeCategory" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Team" ADD FOREIGN KEY ("ownerId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TeamMember" ADD FOREIGN KEY ("teamId") REFERENCES "Team" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TeamMember" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TeamMember" ADD FOREIGN KEY ("positionId") REFERENCES "TeamPosition" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentRegistration" ADD FOREIGN KEY ("tournamentId") REFERENCES "Tournament" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentRegistration" ADD FOREIGN KEY ("teamId") REFERENCES "Team" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentRegistration" ADD FOREIGN KEY ("registrationStatusId") REFERENCES "StatusMaster" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentRegistrationPayment" ADD FOREIGN KEY ("registrationId") REFERENCES "TournamentRegistration" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentAnnouncement" ADD FOREIGN KEY ("tournamentId") REFERENCES "Tournament" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentFAQ" ADD FOREIGN KEY ("tournamentId") REFERENCES "Tournament" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentFAQ" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Campaign" ADD FOREIGN KEY ("brandId") REFERENCES "BrandDetails" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Campaign" ADD FOREIGN KEY ("campaignTypeId") REFERENCES "CampaignType" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Campaign" ADD FOREIGN KEY ("gameId") REFERENCES "Game" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CampaignPlatform" ADD FOREIGN KEY ("campaignId") REFERENCES "Campaign" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CampaignPlatform" ADD FOREIGN KEY ("platformId") REFERENCES "SocialMediaPlatform" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CampaignAsset" ADD FOREIGN KEY ("campaignId") REFERENCES "Campaign" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CampaignDeliverable" ADD FOREIGN KEY ("campaignId") REFERENCES "Campaign" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CollaborationRequest" ADD FOREIGN KEY ("senderId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CollaborationRequest" ADD FOREIGN KEY ("receiverId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CollaborationRequest" ADD FOREIGN KEY ("campaignId") REFERENCES "Campaign" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RevenueTransaction" ADD FOREIGN KEY ("transactionTypeId") REFERENCES "TransactionType" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RevenueTransaction" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RevenueTransaction" ADD FOREIGN KEY ("paymentMethodId") REFERENCES "PaymentMethod" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentPayment" ADD FOREIGN KEY ("organizerId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentPayment" ADD FOREIGN KEY ("tournamentId") REFERENCES "Tournament" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TournamentPayment" ADD FOREIGN KEY ("packageId") REFERENCES "TournamentPackage" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "UserSubscription" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "UserSubscription" ADD FOREIGN KEY ("subscriptionPlanId") REFERENCES "SubscriptionPlan" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Notification" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AuditLog" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
